"""Add system_settings table for email configuration

Revision ID: c8cb01c4849d
Revises: 28ad91c6ab70
Create Date: 2025-10-31 02:50:17.404321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cb01c4849d'
down_revision: Union[str, None] = '28ad91c6ab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
