"""Add missing columns to HubInvoice model for service compatibility

Revision ID: 28ad91c6ab70
Revises: 003
Create Date: 2025-10-31 02:47:50.383653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28ad91c6ab70'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendors_accounting_vendor_id', table_name='vendors')
    op.drop_index('ix_vendors_id', table_name='vendors')
    op.drop_index('ix_vendors_inventory_vendor_id', table_name='vendors')
    op.drop_index('ix_vendors_name', table_name='vendors')
    op.drop_table('vendors')
    op.add_column('hub_invoices', sa.Column('inventory_invoice_id', sa.Integer(), nullable=True))
    op.add_column('hub_invoices', sa.Column('accounting_je_id', sa.Integer(), nullable=True))
    op.add_column('hub_invoices', sa.Column('inventory_error', sa.Text(), nullable=True))
    op.add_column('hub_invoices', sa.Column('accounting_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub_invoices', 'accounting_error')
    op.drop_column('hub_invoices', 'inventory_error')
    op.drop_column('hub_invoices', 'accounting_je_id')
    op.drop_column('hub_invoices', 'inventory_invoice_id')
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('inventory_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accounting_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey')
    )
    op.create_index('ix_vendors_name', 'vendors', ['name'], unique=False)
    op.create_index('ix_vendors_inventory_vendor_id', 'vendors', ['inventory_vendor_id'], unique=False)
    op.create_index('ix_vendors_id', 'vendors', ['id'], unique=False)
    op.create_index('ix_vendors_accounting_vendor_id', 'vendors', ['accounting_vendor_id'], unique=False)
    # ### end Alembic commands ###
