"""Add mapping tables

Revision ID: d609c0b4e864
Revises: 534492aec643
Create Date: 2025-10-31 04:09:26.755726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd609c0b4e864'
down_revision: Union[str, None] = '534492aec643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendors_accounting_vendor_id', table_name='vendors')
    op.drop_index('ix_vendors_id', table_name='vendors')
    op.drop_index('ix_vendors_inventory_vendor_id', table_name='vendors')
    op.drop_index('ix_vendors_name', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_system_settings_category', table_name='system_settings')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('category_gl_mapping', sa.Column('gl_revenue_account', sa.Integer(), nullable=True))
    op.add_column('category_gl_mapping', sa.Column('asset_account_name', sa.String(length=200), nullable=True))
    op.add_column('category_gl_mapping', sa.Column('cogs_account_name', sa.String(length=200), nullable=True))
    op.add_column('category_gl_mapping', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('category_gl_mapping', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('category_gl_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_gl_mapping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_category_gl_mapping_category', table_name='category_gl_mapping')
    op.drop_constraint('uq_category_gl_mapping_category', 'category_gl_mapping', type_='unique')
    op.create_index(op.f('ix_category_gl_mapping_id'), 'category_gl_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_category_gl_mapping_inventory_category'), 'category_gl_mapping', ['inventory_category'], unique=True)
    op.drop_column('category_gl_mapping', 'display_name')
    op.alter_column('hub_invoice_items', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hub_invoice_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('hub_invoice_items', 'is_mapped',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_hub_invoice_items_id'), 'hub_invoice_items', ['id'], unique=False)
    op.drop_constraint('hub_invoice_items_invoice_id_fkey', 'hub_invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'hub_invoice_items', 'hub_invoices', ['invoice_id'], ['id'])
    op.drop_column('hub_invoice_items', 'line_total')
    op.alter_column('hub_invoices', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('hub_invoices', 'pdf_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('hub_invoices', 'sent_to_inventory',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoices', 'sent_to_accounting',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('hub_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hub_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_hub_invoices_invoice_date', table_name='hub_invoices')
    op.drop_index('ix_hub_invoices_vendor_name', table_name='hub_invoices')
    op.drop_constraint('uq_hub_invoices_invoice_hash', 'hub_invoices', type_='unique')
    op.drop_index('ix_hub_invoices_invoice_hash', table_name='hub_invoices')
    op.create_index(op.f('ix_hub_invoices_invoice_hash'), 'hub_invoices', ['invoice_hash'], unique=True)
    op.create_index(op.f('ix_hub_invoices_created_at'), 'hub_invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_hub_invoices_id'), 'hub_invoices', ['id'], unique=False)
    op.drop_column('hub_invoices', 'created_by_id')
    op.add_column('item_gl_mapping', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('vendor_item_code', sa.String(length=100), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('gl_revenue_account', sa.Integer(), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('asset_account_name', sa.String(length=200), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('cogs_account_name', sa.String(length=200), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('item_gl_mapping', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('item_gl_mapping', 'inventory_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('item_gl_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('item_gl_mapping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_item_gl_mapping_category', table_name='item_gl_mapping')
    op.drop_constraint('uq_item_gl_mapping_inventory_item_id', 'item_gl_mapping', type_='unique')
    op.create_index(op.f('ix_item_gl_mapping_id'), 'item_gl_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_item_gl_mapping_inventory_category'), 'item_gl_mapping', ['inventory_category'], unique=False)
    op.create_index(op.f('ix_item_gl_mapping_is_active'), 'item_gl_mapping', ['is_active'], unique=False)
    op.create_index(op.f('ix_item_gl_mapping_vendor_id'), 'item_gl_mapping', ['vendor_id'], unique=False)
    op.create_unique_constraint('uq_inventory_item_mapping', 'item_gl_mapping', ['inventory_item_id'])
    op.drop_column('item_gl_mapping', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_gl_mapping', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_inventory_item_mapping', 'item_gl_mapping', type_='unique')
    op.drop_index(op.f('ix_item_gl_mapping_vendor_id'), table_name='item_gl_mapping')
    op.drop_index(op.f('ix_item_gl_mapping_is_active'), table_name='item_gl_mapping')
    op.drop_index(op.f('ix_item_gl_mapping_inventory_category'), table_name='item_gl_mapping')
    op.drop_index(op.f('ix_item_gl_mapping_id'), table_name='item_gl_mapping')
    op.create_unique_constraint('uq_item_gl_mapping_inventory_item_id', 'item_gl_mapping', ['inventory_item_id'])
    op.create_index('ix_item_gl_mapping_category', 'item_gl_mapping', ['inventory_category'], unique=False)
    op.alter_column('item_gl_mapping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('item_gl_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('item_gl_mapping', 'inventory_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('item_gl_mapping', 'notes')
    op.drop_column('item_gl_mapping', 'created_by')
    op.drop_column('item_gl_mapping', 'is_active')
    op.drop_column('item_gl_mapping', 'cogs_account_name')
    op.drop_column('item_gl_mapping', 'asset_account_name')
    op.drop_column('item_gl_mapping', 'gl_revenue_account')
    op.drop_column('item_gl_mapping', 'vendor_item_code')
    op.drop_column('item_gl_mapping', 'vendor_id')
    op.add_column('hub_invoices', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hub_invoices_id'), table_name='hub_invoices')
    op.drop_index(op.f('ix_hub_invoices_created_at'), table_name='hub_invoices')
    op.drop_index(op.f('ix_hub_invoices_invoice_hash'), table_name='hub_invoices')
    op.create_index('ix_hub_invoices_invoice_hash', 'hub_invoices', ['invoice_hash'], unique=False)
    op.create_unique_constraint('uq_hub_invoices_invoice_hash', 'hub_invoices', ['invoice_hash'])
    op.create_index('ix_hub_invoices_vendor_name', 'hub_invoices', ['vendor_name'], unique=False)
    op.create_index('ix_hub_invoices_invoice_date', 'hub_invoices', ['invoice_date'], unique=False)
    op.alter_column('hub_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hub_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hub_invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('hub_invoices', 'sent_to_accounting',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoices', 'sent_to_inventory',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoices', 'pdf_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('hub_invoices', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('hub_invoice_items', sa.Column('line_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hub_invoice_items', type_='foreignkey')
    op.create_foreign_key('hub_invoice_items_invoice_id_fkey', 'hub_invoice_items', 'hub_invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hub_invoice_items_id'), table_name='hub_invoice_items')
    op.alter_column('hub_invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hub_invoice_items', 'is_mapped',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hub_invoice_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('hub_invoice_items', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('category_gl_mapping', sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_category_gl_mapping_inventory_category'), table_name='category_gl_mapping')
    op.drop_index(op.f('ix_category_gl_mapping_id'), table_name='category_gl_mapping')
    op.create_unique_constraint('uq_category_gl_mapping_category', 'category_gl_mapping', ['inventory_category'])
    op.create_index('ix_category_gl_mapping_category', 'category_gl_mapping', ['inventory_category'], unique=False)
    op.alter_column('category_gl_mapping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_gl_mapping', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('category_gl_mapping', 'notes')
    op.drop_column('category_gl_mapping', 'is_active')
    op.drop_column('category_gl_mapping', 'cogs_account_name')
    op.drop_column('category_gl_mapping', 'asset_account_name')
    op.drop_column('category_gl_mapping', 'gl_revenue_account')
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_index('ix_system_settings_category', 'system_settings', ['category'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('inventory_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accounting_vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey')
    )
    op.create_index('ix_vendors_name', 'vendors', ['name'], unique=False)
    op.create_index('ix_vendors_inventory_vendor_id', 'vendors', ['inventory_vendor_id'], unique=False)
    op.create_index('ix_vendors_id', 'vendors', ['id'], unique=False)
    op.create_index('ix_vendors_accounting_vendor_id', 'vendors', ['accounting_vendor_id'], unique=False)
    # ### end Alembic commands ###
