# Pydantic schemas
from accounting.schemas.vendor_bill import (
    VendorBillCreate,
    VendorBillUpdate,
    VendorBillResponse,
    VendorBillListResponse,
    VendorBillLineCreate,
    VendorBillLineUpdate,
    VendorBillLineResponse,
    BillApprovalRequest,
    BillPaymentCreate,
    BillPaymentResponse,
    APAgingReportResponse,
    AgingBucket,
    VendorAgingDetail,
)

from accounting.schemas.bank_account import (
    BankAccountCreate,
    BankAccountUpdate,
    BankAccountResponse,
    BankTransactionCreate,
    BankTransactionUpdate,
    BankTransactionResponse,
    BankStatementImportCreate,
    BankStatementImportResponse,
    BankReconciliationCreate,
    BankReconciliationUpdate,
    BankReconciliationResponse,
    BankReconciliationItemCreate,
    BankReconciliationItemResponse,
    BankMatchingRuleCreate,
    BankMatchingRuleUpdate,
    BankMatchingRuleResponse,
    PlaidLinkTokenRequest,
    PlaidLinkTokenResponse,
    PlaidPublicTokenExchange,
    PlaidAccountResponse,
    PlaidSyncRequest,
    PlaidSyncResponse,
    TransactionMatchSuggestion,
    TransactionMatchRequest,
    TransactionUnmatchRequest,
    FileUploadResponse,
)

from accounting.schemas.bank_statement import (
    BankStatement,
    BankStatementCreate,
    BankStatementUpdate,
    StatementSummary,
    MatchSuggestionResponse,
    MatchSuggestionsResponse,
    ConfirmMatchRequest,
    ConfirmMatchResponse,
    CompositeMatchRequest as CompositeMatchRequestOld,  # Phase 1A version
    BankMatchingRule as BankMatchingRuleV2,
    BankMatchingRuleCreate as BankMatchingRuleV2Create,
    BankMatchingRuleUpdate as BankMatchingRuleV2Update,
    CreateRuleFromMatchRequest,
)

from accounting.schemas.composite_match import (
    CompositeMatchLineCreate,
    CompositeMatchLineResponse,
    CompositeMatchRequest,  # Phase 1B version
    CompositeMatchResponse,
    CompositeMatchSummary,
    UndepositedFundsLine,
    UndepositedFundsRequest,
    UndepositedFundsResponse,
    CompositeMatchSuggestion,
    CompositeMatchSuggestionsResponse,
    UnmatchCompositeRequest,
    UnmatchCompositeResponse,
)

from accounting.schemas.banking_dashboard import (
    DailyCashPosition,
    DailyCashPositionCreate,
    CashFlowTransaction,
    CashFlowTransactionCreate,
    CashFlowSummary as DashboardCashFlowSummary,  # Renamed to avoid conflict
    BankingAlert,
    BankingAlertCreate,
    AlertAcknowledge,
    AlertResolve,
    ReconciliationHealthMetric,
    ReconciliationHealthMetricCreate,
    LocationCashFlowSummary,
    LocationCashFlowSummaryCreate,
    DashboardKPI,
    LocationSummary,
    DashboardSummaryResponse,
    CashFlowTrendPoint,
    CashFlowTrendResponse,
    ReconciliationTrendPoint,
    ReconciliationTrendResponse,
)

from accounting.schemas.cash_flow import (
    CashFlowLineItem,
    CashFlowSection,
    CashFlowStatementResponse,
    CashFlowSummary,
    CashFlowComparison,
)

from accounting.schemas.general_dashboard import (
    ExecutiveSummaryMetrics,
    ExecutiveSummaryResponse,
    TopExpenseCategory,
    LocationRevenue,
    DailySalesMetrics,
    COGSMetrics,
    BankBalanceSummary,
    CashFlowForecast,
    APAgingSummary,
    AccountingHealthMetrics,
    RealTimeTrackingResponse,
    MonthlyPerformancePoint,
    HistoricalTrendResponse,
    BudgetVarianceItem,
    BudgetVarianceResponse,
    LocationPerformanceFlag,
    LocationPerformanceMetrics,
    MultiLocationResponse,
    DashboardAlertResponse,
    AlertAcknowledgeRequest,
    AlertResolveRequest,
    AlertSummaryResponse,
    DashboardSummaryResponse,
    MonthEndChecklistItem,
    MonthEndCloseStatus,
)

__all__ = [
    "VendorBillCreate",
    "VendorBillUpdate",
    "VendorBillResponse",
    "VendorBillListResponse",
    "VendorBillLineCreate",
    "VendorBillLineUpdate",
    "VendorBillLineResponse",
    "BillApprovalRequest",
    "BillPaymentCreate",
    "BillPaymentResponse",
    "APAgingReportResponse",
    "AgingBucket",
    "VendorAgingDetail",
    "BankAccountCreate",
    "BankAccountUpdate",
    "BankAccountResponse",
    "BankTransactionCreate",
    "BankTransactionUpdate",
    "BankTransactionResponse",
    "BankStatementImportCreate",
    "BankStatementImportResponse",
    "BankReconciliationCreate",
    "BankReconciliationUpdate",
    "BankReconciliationResponse",
    "BankReconciliationItemCreate",
    "BankReconciliationItemResponse",
    "BankMatchingRuleCreate",
    "BankMatchingRuleUpdate",
    "BankMatchingRuleResponse",
    "PlaidLinkTokenRequest",
    "PlaidLinkTokenResponse",
    "PlaidPublicTokenExchange",
    "PlaidAccountResponse",
    "PlaidSyncRequest",
    "PlaidSyncResponse",
    "TransactionMatchSuggestion",
    "TransactionMatchRequest",
    "TransactionUnmatchRequest",
    "FileUploadResponse",
    "BankStatement",
    "BankStatementCreate",
    "BankStatementUpdate",
    "StatementSummary",
    "MatchSuggestionResponse",
    "MatchSuggestionsResponse",
    "ConfirmMatchRequest",
    "ConfirmMatchResponse",
    "CompositeMatchRequest",
    "BankMatchingRuleV2",
    "BankMatchingRuleV2Create",
    "BankMatchingRuleV2Update",
    "CreateRuleFromMatchRequest",
    # Phase 1B Composite Matching
    "CompositeMatchLineCreate",
    "CompositeMatchLineResponse",
    "CompositeMatchRequest",
    "CompositeMatchResponse",
    "CompositeMatchSummary",
    "UndepositedFundsLine",
    "UndepositedFundsRequest",
    "UndepositedFundsResponse",
    "CompositeMatchSuggestion",
    "CompositeMatchSuggestionsResponse",
    "UnmatchCompositeRequest",
    "UnmatchCompositeResponse",
    # Banking Dashboard
    "DailyCashPosition",
    "DailyCashPositionCreate",
    "CashFlowTransaction",
    "CashFlowTransactionCreate",
    "CashFlowSummary",
    "BankingAlert",
    "BankingAlertCreate",
    "AlertAcknowledge",
    "AlertResolve",
    "ReconciliationHealthMetric",
    "ReconciliationHealthMetricCreate",
    "LocationCashFlowSummary",
    "LocationCashFlowSummaryCreate",
    "DashboardKPI",
    "LocationSummary",
    "DashboardSummaryResponse",
    "CashFlowTrendPoint",
    "CashFlowTrendResponse",
    "ReconciliationTrendPoint",
    "ReconciliationTrendResponse",
    # Cash Flow Statement
    "CashFlowLineItem",
    "CashFlowSection",
    "CashFlowStatementResponse",
    "CashFlowSummary",
    "CashFlowComparison",
    "DashboardCashFlowSummary",
    # General Dashboard
    "ExecutiveSummaryMetrics",
    "ExecutiveSummaryResponse",
    "TopExpenseCategory",
    "LocationRevenue",
    "DailySalesMetrics",
    "COGSMetrics",
    "BankBalanceSummary",
    "CashFlowForecast",
    "APAgingSummary",
    "AccountingHealthMetrics",
    "RealTimeTrackingResponse",
    "MonthlyPerformancePoint",
    "HistoricalTrendResponse",
    "BudgetVarianceItem",
    "BudgetVarianceResponse",
    "LocationPerformanceFlag",
    "LocationPerformanceMetrics",
    "MultiLocationResponse",
    "DashboardAlertResponse",
    "AlertAcknowledgeRequest",
    "AlertResolveRequest",
    "AlertSummaryResponse",
    "DashboardSummaryResponse",
    "MonthEndChecklistItem",
    "MonthEndCloseStatus",
]
